### ISSUE TITLE
script js doesn't work

### ISSUE THREAD

**Issue by matthewdking** [facn2/The-Powerpuff-Girls#61]
the script file has an error on the console
```
home:47 GET http://localhost:4000/public/index.js 500 (Content-Type: text/html)
```
the content type should be js not html

**Comment by matthewdking** [comment]
the file name has actually changed from index.js to script.js but wasn't changed in the index.html

https://github.com/facn2/The-Powerpuff-Girls/blob/master/public/home.html#L47

**Comment by KatiaAsh** [comment]
We have change the js file name
@matthewdking Please have a look and close the issue :+1:
